
// Match API Failure reasons
export enum MatchErrorReason{
    INVALID_REQUEST = "INVALID_REQUEST",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    RESUME_NOT_FOUND = "RESUME_NOT_FOUND",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    UNSUPPORTED_SCHEMA = "UNSUPPORTED_SCHEMA"
}

// Job Role API Failure reasons
export enum JobRoleErrorReason{
    INVALID_REQUIREMENTS = "INVALID_REQUIREMENTS",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    DUPLICATE_ROLE = "DUPLICATE_ROLE"
}

